name: LightTag
version: '0.1'
main: ink.neokoni.lightTag.LightTag
loader: ink.neokoni.lightTag.LightTagLoader
api-version: '1.20.6'
authors: [ Neokoni ]
website: https://github.com/Neokoni/LightTag
contributors: [Jason31416]

folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
permissions:
  lighttag.*:
    description: "LightTag Full permission"
    default: op
    children:
      - lighttag.reload
      - lighttag.add
      - lighttag.give
      - lighttag.save
      - lighttag.set
      - lighttag.list
      - lighttag.clear
      - lighttag.help
      - lighttag.debug
      - lighttag.buy
  lighttag.player:
    description: "Our recommend permissions for common players"
    children:
      - lighttag.set
      - lighttag.list
      - lighttag.clear
      - lighttag.help
      - lighttag.buy